### ISSUE TITLE
42: het zou zeer handig zijn als ge ergens gemakkelijk de recentste bewerkingen zou kunnen bekijken, dan is het niet meer nodig van de profielen van de recent actieve gebruikers continu te bespioneren. Er bestaat nu al een dergelijke functie voor de recent

### ISSUE THREAD

**Issue by nathansamson** [vlaamswoordenboek/vlaamswoordenboek.be#141]
42: het zou zeer handig zijn als ge ergens gemakkelijk de recentste bewerkingen zou kunnen bekijken, dan is het niet meer nodig van de profielen van de recent actieve gebruikers continu te bespioneren. Er bestaat nu al een dergelijke functie voor de recentste reacties op http://www.vlaamswoordenboek.be/definities/reacties

Van: nthn

**Comment by Georges-Grootjans** [comment]
Vroeger was er in het bedieningspaneel aan de linkerkant een knop voor 'recente reacties', maar Anthony Liekens heeft die knop op een bepaald moment weggehaald om een of andere reden.

**Comment by nathansamson** [comment]
![image](https://user-images.githubusercontent.com/93735/130499592-612406ba-f224-41b8-822c-cd85ccb9f221.png)

Deze staan nu rechts. Enkel voor ingelogde admins
