### ISSUE TITLE
Oproep voor Kies je favoriete woord staat nog steeds op VW

### ISSUE THREAD

**Issue by Georges-Grootjans** [vlaamswoordenboek/vlaamswoordenboek.be#303]
De enquête is reeds lang afgelopen en de link werkt overigens niet meer. Misschien best verwijderen en terug de link naar de github plaatsen?

**Comment by nathansamson** [comment]
@Georges-Grootjans bedankt voor de reminder. Eindelijk eens 5 min tijd gevonden om het aan te passen
