### ISSUE TITLE
Knop "Recent" werkt niet (meer)

### ISSUE THREAD

**Issue by Georges-Grootjans** [vlaamswoordenboek/vlaamswoordenboek.be#84]
Na invoeren van lemma "stroop aan de baard smeren" https://vlaamswoordenboek.be/definities/term/iemand%20stroop%20aan%20de%20baard%20smeren
werkt knop 'recent' niet meer. Het lemma "stroop aan de baard smeren"  kan ook niet opgehaald worden.

**Comment by nathansamson** [comment]
Bedankt @Georges-Grootjans 

Het probleem zou nu moeten zijn opgelost. Ook als er nog neiuwe woorden worden toegevoegd!

Laat gerust iets weten mocht je nog andere problemen zien, of dit toch nog niet helemaal in orde is
