### ISSUE TITLE
Recente gebruikers worden nog niet goed weergegeven:

### ISSUE THREAD

**Issue by Georges-Grootjans** [vlaamswoordenboek/vlaamswoordenboek.be#86]
Er zijn momenteel 11253 gebruikers geregistreerd op het Vlaams woordenboek. De meest recentelijk geregistreerde gebruikers zijn <a href="/users/harthoorn">harthoorn</a>, <a href="/users/Veerle%20Vandueren">Veerle Vandueren</a>, <a href="/users/J.%20Arickx">J. Arickx</a>, <a href="/users/PEOost">PEOost</a>, <a href="/users/WilanashGumbene">WilanashGumbene</a>.

**Comment by Georges-Grootjans** [comment]
Euh… hier werkt de link dus wel maar in het VW niet.

**Comment by nathansamson** [comment]
Deze links tonen nu normaal correct. Laat maar weten mocht je nog andere voorbeelden vinden die nog steeds niet werken

**Comment by nathansamson** [comment]
https://vlaamswoordenboek.be/users werkt nu wel correct.

Lijkt er wel op dat er paar accounts tussen zitten die door bots zijn aangemaakt. @aliekens  is dat iets waar je vroeger ook al last van had en gewoon negeerde, of is dit omdat zelf russische bots non-https sites negeren?
