### ISSUE TITLE
slechte weergave van sommige karakters

### ISSUE THREAD

**Issue by Georges-Grootjans** [vlaamswoordenboek/vlaamswoordenboek.be#87]
zie: https://vlaamswoordenboek.be/definities/18177

**Comment by nathansamson** [comment]
@Georges-Grootjans ik had het ook al gemerkt in

https://github.com/vlaamswoordenboek/vlaamswoordenboek.be/issues/12

(ander voorbeeldje) https://red.vlaamswoordenboek.be/definities/term/schab

Ik zoek zo snel mogelijk naar een oplossing

**Comment by nathansamson** [comment]
Deze links tonen nu normaal correct. Laat maar weten mocht je nog andere voorbeelden vinden die nog steeds niet werken
