### ISSUE TITLE
error in link naar gebruiker

### ISSUE THREAD

**Issue by Georges-Grootjans** [vlaamswoordenboek/vlaamswoordenboek.be#91]
Bij https://vlaamswoordenboek.be/definities/16570 is de tweede reactie van  betty.vanmechelen@telenet.be . Normaal kun je op een user klikken om zijn profiel te zien, maar met dit e-mailadres lukt dat niet en krijgt je een error.

**Comment by nathansamson** [comment]
Deze link werkt nu correct
