### ISSUE TITLE
tijdszone klok

### ISSUE THREAD

**Issue by Georges-Grootjans** [vlaamswoordenboek/vlaamswoordenboek.be#92]
voorbeeld: https://vlaamswoordenboek.be/definities/term/van%20bachten%20de%20Kupe%20zijn%20of%20komen

Werd 19 Aug 2021 06:09 ingevoerd, maar de geregistreerde tijd in het lemma is 19 Aug 2021 04:09.

**Comment by nathansamson** [comment]
Tijd wordt nu wel correct getoond
